dist: trusty
services:
  - docker
language: node_js
node_js:
  - '11'
after_success:
  - docker build -t jerrytfleung/primality .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push jerrytfleung/primality
env:
  global:
    - secure: 28Ufnl4YhAb3ewE+KzSf15qCn7P7vZIywIE1z/tmyhp9oQdqmYiLGrYeg0r4F8S6sBLeKibTV/FVvGCB7+1c9A4bF68LcvcnCRaB7TvOLKZlO6beNgfGlZL+35KdlJBJ3zJEUCEvQv21Jc3sdgxxeAbNRdHCfzuMkidzP6KMOFPhdda+xgg11LeVyForr4cl13o5OPZMKqjk/xKalWCw3r5e2+y0kaTDAivrPMvS7mfMELSHBCt3oQ1vva3iX4bDwlP20owH4eOBt+YZ5Ln0RZiLcE4ntLTLhUhIoYGT3JQq5UEqYPLk9A0/7LYYKp3nBiEg4/cUDAh/hqb234dJFNcJMt5YyP/OYWGjQYHwNCpDF9nAgeuwIY1YJHvBYafJfmgAFY+QeR+pg6tHHbk28KDy0NE4FLHcxLgjJ1F9W0vMWel1xZN11Lt3mi2eDyafEMYx/NVsjkZOUfsGjy1bz5VF3mmS4d435D16Lsod/xNyAxwtLC/e56aGRcUIQXLxoggYTtOFY3/031r5Gtbw7CVLRPZV4dAFa8nx9HzJQHR+GC8qCNWyKGv1DPq9bjbJW8duSv2IeEbiDJeo06d1H/ypDZT0oa0B2Qn3lwNlIq4XVWktCSjPOGlIxweW0Pix1e0PxMcB2Ju3A59xz5zHVQY1gTnA7tQHHNWq7Fa3hlA=
    - secure: f3TV7ZswqX4fYxsUkUptGLWKTMsKV/UHYSlDRK4dw28e13lIySxtT2IxWo4F3inZn+0v21DJnwgfSdlX9nFsUjbhLDIrmV4a4CibWhPwyDhXy1MCyZjIJzKC8H56RAfP3wPEiUs4f4CkRPVAOtQXjYPfEq70SsyiIbhIkZc5o6T9xNbekC4U4zgFcD2EmXLw/WdN34FHRgy/CZ5L5tXgbf8kUxCVAQI0/4GsfxH7EMfIwMBHR1+E6qC+u/zz+v5845nQycHiAXJW8bihZeu77N+X/1IgNZLkVUB+HTUbAnESPHuYf4UtY/AT+iI4nMNg3gD/k5oY0saIjk6Kiy8ZIkepCdRwLjVK8gXsc89FjrOqSCPu3heknSCbsjljZMbCZkA4k3f3QGeAHheoXyTzk7+dbD2xAn/t7C65UTFSQURYmb9s82GKsA1vcHXNi1TAscV8hxTRWvHNNLpDEvUUSVfWWxHMOR2HxVnXsjI8sTeRSqUyWSmrqCwvm9cEnYjRHUpan/ZvIj5pIL+WRT0cIDoxMi2huw5LKcSMOPBfEoGgTk1nycsggVBx8XfhFZ8UALaHnwPZScRewQlO6pZjY4o9tDu7BVwDVSsa1v7OUo3+yEZSahGgi4LX7teJ/deulZL6BLNkMuL6QvBrY9dwCcl/5hBtCBl5BQQcCOKx23o=
