sudo: required
services:
  - docker
dist: trusty
language: node_js
node_js:
  - '11'
after_success:
  - docker build -t jerrytfleung/primality .
after_script:
  - docker images
before_deploy:
  - echo "$REGISTRY_PASS" | docker login --username "$REGISTRY_USER" --password-stdin
deploy:
  provider: script
  script: docker push jerrytfleung/primality
  on:
    branch: master
env:
  global:
    - secure: 2fvAithETvI0OSEy9pRsnn7AHBvcRkkYWFK7igvpLhRoeevXYfEtvwUml+UPsH46LcRhK8bfNShOhBaSXeHmSoQywjGmBG77WaT0tpVD73bwLHny6kFhA10Oj0inANlmoy4ndRf4U762lNomKbEUOIGMeXOMFTYkijIeQitlAwFxz2MxznkoFyfvW/nlJ/1s5gKx8EJKnRrkHHenBTlEMYLoY0tHMVwHf29feqrYtO9wgiLXVtYLWPRknTQkrTLcmqVXzRZUD02YsXpW45zBOs3vZiTAv01KypqWKtpmx6eC7FPejTxWj7L5/axN7PKDDHhdbLhDqfBuJn9w3SbBEsNMlrUlL6uv8JO0FgSvmvaqEOWFij4cFPXsUtBeq92CdHOM9IsQDq5Ti3h2x48REGtrlmFmAQY7WBCo0hV0TsaR0jNc5YGKx25pmLosUqfheY+uQuR7y8lhqAfX3VqpJzMMIQ/sxftTA4KOU5HFabBikH05FJS41Wtlx6cUjP3KaDlhAQZGDhHm5z56Uyv20mGwV9z5+g4IXchCpugozMzY2fJBtlbuPJ+4jmMz29d3gB1jpDjPeEeVRr21QWrHPUQam+MDcMxTmlF6tJ8hvVEsGZNp8BTa/fRj6Kvp9ZIdj4vC/72fqPFVKwPlak1QZXX2p87uuUI3aLmJcmPZmFg=
    - secure: VPRo9NRgJGufiCjYjgYO5j4kqOcgwA/gBMxUcDIY6KHCtPswSlzucImxs3Jl+ssIsdDDQukYcaEi3qcavoZERXkkbbDx/F/PtTDQn+d63fEBW4L4/J6oQ2xqynAQ7XPBLniK0UHp/Yi1T8qy6oJxF4n7OwY7ClCP/u0zLc+Pt/Mk85DpFTby3q6WaTHbI14uKLXjzT/MjswTJ6bSzmg4RHFCs4SpSTvMRPURryqRqgIkoEsUyQ5lNlV5AhIKpfhi705tUTbvemfI+kbXF0TQFtn2iKTwQ8SKej3JAuPVFKQ4F/wwlu3dxDFgp2ZvkAPQ0bDPRkdzsgtjqDYhwBjEw/+p3aNuf4ATzJn1v7ZC7Fs4IrNnG3LsT4r1zbuXD0iSfv4HiTTKyubjOfOsVKydnxwlRRHjyUO8soi7TJpmrududi1Lcu5MLlnIa2uisWj+Ni1Ad/wBMiYpcEqo5y7QjtjZCTSdq7IDxqU6qYYPs+8Nb01/TZKejneCTTRQ/YV2b3VDH9xzRcejn1nLCSR3AhQcZlt3AahmSCMcgPQTh17x+8Q3Ducr5f2oKr9y3JAIoiadL0XT6/w7aqi6mqhZscJy+hPaK/w7nh1hzCc8LiNmINS0NXfq0uy69VC9W6JPR8qgjp4M3CCpgqCByDTLCOGgCDveJWuYOked8P8ts00=
