sudo: required
services:
  - docker
dist: trusty
language: node_js
node_js:
  - '11'
after_success:
  - docker build -t jerrytfleung/primality .
after_script:
  - docker images
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push jerrytfleung/primality
  on:
    branch: master
env:
  matrix:
    - secure: 3NrVvb5vOoJqm1/FPLY9B9qL/xZ3ZHWVyG+BUkF7oWqCTfT//T47TbXIjTNfrU/fON9CpoyD7Qd1lLVvuA2NRbiFx9+joH549CVyanBBmASmFVnOZrfjKjsIBUdmB3/LMl9AVk4irWi8v4c98zIGr3PQDLHvcoWx2aMUb8kVu9SQUoG4vYudtj0TSojDFS9cbq/eGt16TNaIb5J0VOpyx2zlpxNhKr3VPHT2pO+j/grsELBihhCPbEYvbey5uUuePBPSxslTv5XocAJGoSw8fCV/xoPWxJhb14h6XpvGJcnD9mylMYRMHK2X/WozlDSsGURBoj9V67KlbahI6HPgyGeWWOlvL1k32CrKh9cv5Z5UggxP5cgP1lykdQFvjgQATZzjgkemxt5HvraHBZmS49Zt8gHe1K8c8p4tn2K0nsikPW/qEGNpdIYNFjPWfsrAdPhzY5oB1cc7go6ithzx2HzXdIiDBSrJlsaBbvgDCo1+sCHFPO8iKDwYDAo7ZpVRVNbXZzIQbPHSf2ySI6efgA6pF3HRaEk4yXniWMjXH/6b3/LMeL8RloaLg3ap0tjVkogLwGkmoNkP9rbUbEIUxEb7mgVzf7VD0Ri3PCx0l6jp2t0yGsxouQYInqQPjThEsearqZEKfbkVcRKCPsZ6yQr7ePdm0SbcF9KA+O+rDQ0=
    - secure: Np61dP8BFqk69DXGphwqmZ635dAl83fAE7Fm4UXMv/qN+9zDRcl+lJqZQAqUYPkwH5qKLnYos/hxGYE4c4drM7wxv6nU2Bfka2moxpb90YXbSBFILpb+bybtyGkWBdhmar6u27y/jK4cRRVjBjH0cRa5e/j34EHCj4sSSSsrUwQh1COwBYRLZXA7izZnlvcKl7eEhR/xs+t4nZNmQxSK5DCnFd3uR5AVRMpK3EA870CMS63J0qjPv9TbGM+UaFemxfyHZyFI93hbGuCpuxIFENyr4pcaLv1HeSCbBLmTuWkHqkPjRHsZGu3vFWPtOEApVe0aB3I2g3Z58t+kMv3LyXy17/5QWwqXGPHnD35WZwWbRHeBoRF1BvygfHMLK3mrUS5ohjmGAXof8I0kFal4je2WbgrJR2Q/BN8+U/2wzE+2riI1ElMmVqWvxSpRbLzEItoJ/v4i8R+6iskiDEBn59IRSd/6kI0gcZJXocoy30cfjWdtsZBS451gO3hEpGSOOxpMCp3A3nYgVsQbWiaDBIWraTVrcaSFQkks8TPjNx/ZEW6LAR87kt+KYyk+8Ol3ee05jqvv6BfxFaajnr6H/HKlSlzoQJpin+C8t9/xlkBRVbe8Zi8kaUrVSD2DYErY4Vql6hltBSi5D2YEf742OyDwnTq3D+BA4VIYvSrP/ys=
