sudo: required
services:
  - docker
dist: trusty
language: node_js
node_js:
  - '11'
after_success:
  - docker build -t jerrytfleung/primality .
after_script:
  - docker images
before_deploy:
  - echo $REGISTRYUSER
  - echo $REGISTRYPASS
  - echo "$REGISTRYPASS" | docker login --username jerrytfleung --password-stdin
deploy:
  provider: script
  script: docker push jerrytfleung/primality
  on:
    branch: master
env:
  global:
    - secure: d3Oug38MPJghgrpLj4aV/1YwG7Uz6M9q8YeTiFJxCfZut1ofR05IS8fkVaUtCRPZwstyeiFjSVsMGj9INkTqjobaehyFUUIBgjQDzGZHf0aT6F4oPUvby40iRKdThDvJvFeOuGDU2PTtMXOnGyj/q5jCWWLvxZHVNd5qSOMcMJIxcRBCiix7gbuJYVHR81dWCspjJqAiKVyDR6xa6Wi7Wn5ScXV1e/lZjaAEhgysMB3QTRBtfY52B6TkI/Wwj4Z+usrEPv+grvAeALReMAAXLUMhNlQVgwIOjs7cRKFVDLn9k/5bk9f/nxlkVP1rwfgqu4wnS8OL3a0zfBgaUUHhALDaLlOGLlThTjG33eMP92MLnhSJez2Bv+p1p1AM0tU+J3u9s4ZzndHaQ8+Sf61ItXymTJmeSvS9ZsJeZaO/Q194SfpBQgoaHYY92gRKM0nHXnZ9U3G3/hU/F4U0C/06TA6HtE3XZ6oi9Sl+fl67EVzEcYp6OUY87xDqdlVtXq66UIl/4womSyVgnWUYvmxub2QpMeuTcncgz9NlFsrJEr70WaNrFKBCh37d7ekMRmlPNCUQtG4/4m5KGShSGkO5N2k/9BphJM13Rjwn00XRw2Stuqz0VM9Gv24CnLgbRk5FvtqLzPUHOvzoVmkQ1WaUz0v0uiOVS1CT23WbObTrAM8=
    - secure: EcqNgpRNjGky9x9/7wtbr3xu5dl/BYe/IiY5xnQLFvBXhi5Q1W6/VcVUO/+shy8txwSJ2TNOQ8gXYcK/T0A32DnWnl1nNC6arLOiwkP/l7ZtyNN1+WCj68oma9e1l2AwB60mP+1HOsUtkIzpYLTUHJU4BGXZuYClvAjPceKtqOzgk2hgjEYo7B/wN5Jr1/Vl2C9lZZOEFZmmGyVirlb0Cj293f+BAoAVw5RiwSIJkpX/1SYDtmV2DSjmR9n0jC3+6z6FEWXML47lM3EMZa4yShPhD4mPepqLtU0p6jE4jIvQeZamZ8jjcX53pIHQf1Cqppxbh5BjbBLEE/6BS3i2RkLCm4I8g1mwya0Z0Oe6qgishyklFwzUucfXr7DR4esGjxuM4tYPdLXF9Jm7OCHU7AW4Glm5yzUCihj9UcwuxsY+2tNLw6ugY2WyAfIXA4Kyrmvn8Y9+EOwSP1pVYccM8UtyuCGDZzCw562NUTuoLjUYC61a6efgo50vzragiP6rQlQAQ9PVMQr4kqNj6ExTRRk0haNEcQkigPc6uMpC/ovY+f7AIVCznn8l82cv84fiHylR4Og0TZM/EEm9Scy9KAR3lkQzx3MD5kAhmMv/4peNH7B/oMzFIQnDqjzrrnm12knBr0ho8Y8DlqtBvZ+4UXvbX3TnZQuRR+J137FW7NA=
