dist: trusty
services:
  - docker
language: node_js
node_js:
  - '11'
after_success:
  - docker build -t jerrytfleung/primality .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jerrytfleung/primality
env:
  global:
    - secure: KPcHLD7z1vqV3lB5DJRtGoHMNuGhIOdYW1fH/mWO6VhItr7+g5LrdwIBCCLUPFAl6egdT3Z6rWsAghB53LF7OueHJtJvr5/cnj+ZJ+6py6WxESFwhmFwsUkbeHs3p1xJmRdDeADc7Nm9Fa8XaJnsOw8LTlf8YrzvIB6hbdONay2UDv5vz6x0QKLiHez2UFbctB7MrJ/JeqezFwPqrjDRVlCGTZDtNuaCf2jQCeAHnT2NqFP6JAdGDir4aKp8zW+cr8UOWzJRVmSeNOOfUiB9OFtdLTCwXwypse/X+v6Y0GBNtlsV7KTjOdaDuErAZVPYJH3NR5lADEl6s3kpD/VMgNHqaVeThsBwe15D467FQYjYni7adiwpGV7tNbv0Pn2o02Vh9SP3RGE5uLuOqTWp9SzV5Zk62Uj2rPEHB7lnV+lM8FSZ7uGuj1HuwOe08kzxqZdQLmPyOtqSFD99v+WKeDwt8WKmsbRLQoz/RZU7f0AxfbMgdXxcRuPiYdCUVaNl6w9Auh+Xkv2xaaReZvGWmZlmEBRLnfneU9+Zyh6+dWbI3ltc8lQxW0AEhK5UZ0VnJsiKhNGv4Pd2h2R4iXB8VolbugHpKEbCsroUlkzdJNjNzE/IFGQXws5qIPycgQFORqCC0KgU8Na9iOyB9ntNZ7AsrqqzDwffnhWEpUsyzeM=
    - secure: r9ui+kZ6Of7cI6Wu6YxwXuE1ziJ8TivOx+FIctjDKVzuC6sAoCUonivgQbLZ+Hw4IFLo632gYzLrpEpAnv90cCUUapM2WD3vge9+M8vyTNQ8e8TdQu3IXTnrT5tSj12BIKY9+hz9TuNY3AokezEuRkEyj2B7ypr5g/5BBZ7kDUUOGRxe5YxrSIIaHyV9S+1Yz94DC4HZYWrJ70lzg4y8VdB9JCUmybE4Y3uRITPANtR6fkt7ZJCuHXArG9kCIs3BgW0BUxO3Jnysy13RVUFgLijrwEAsxr16RHXdue6eB0J/fj44XBhEXmaTqh9PxAIYnCCpcXEQ4NoRqDPvOgiWsveQ1RNhDzhV7Mbp/Y+5X4mtaWsuNryKIK+fU8NKHXbg5WLC+jkqzrB/pNsx0siCAH5IWZ+GYj+/emlyS5KAuh1wjr3yKF4G9eUsujyErqpIPwXwMCyNKUfwDcmtfjGGfvlv3v9dgTsv1tVIl2IS3K9guacpPQSutU26Fpj2zjgDLoJSXJcW+kn9dtp6PBFpEzBb25G84DO0Phi0VeD3TiHykY78tgzUPm4n2aGXMJw9ZcdajYz6GX9a3Bi7YGq+J/rS4xxGlVw66LTsvdEV1IZ5/59St8nyiqMr0LT0TVPB/h3gA+OcrGThtrs+SWuRbd19f4ExTQMoIL7p01jfYqA=
