sudo: required
services:
  - docker
dist: trusty
language: node_js
node_js:
  - '11'
after_success:
  - docker build -t jerrytfleung/primality .
after_script:
  - docker images
before_deploy:
  - echo "$REGISTRY_PASS" | docker login --username "$REGISTRY_USER" --password-stdin
deploy:
  provider: script
  script: docker push jerrytfleung/primality
  on:
    branch: master
env:
  global:
    - secure: GcRJbuLUTB3y+xRWTosZRi/29Ovp3DtkcsdQ1AbimFULrebLa0GYh763RNnPyt+1Ka/4raQWxDa7vgEf6ERGlubzQ5mtTB44/4gEtot3D5bLLxmBQmjyzk2ylbf0k1jl+n5IYHJmbxglPGPYZsRtZXei26sl9oHVveg5Ogb/Dn5uc0svDEKF5oZIBzhlihVo+9nM8dcLY/LZbqFpYxDhgzJm1pEUD4kBrNoHe+fzwwtXvI6jssyXfsTF/mLDyslLd47toM/s1mKQO62n+qMpmTDxRvW4FcDbbReBy6da7vha6DOwrzpzCcTDRxnswr80L0G8kr+KYFmDoOP6NCqv8jW9j/GLrZm2RaNSsP/2eFNgvDn0zPBxyIGLXgqARQQDzh6PZvw1JP0ObG6+1OiZ9LGhyfb9Kie/YtO5R5GIXTIMQHsV6Kz/ry+4lShSpBmbm5qFdhuROtnQzZbfjA5u9rqshOLeJYQ7qynpKW+ZSzF6JnYdG1BJdfNlYVowQcOdvvWU3xJs9yhmaGoBRjOMrjRxdfwtuicNL/cd5zqO0r3Max0uPfuEG8yMVMGBRM+15mwaA2/coj2URVdw5u0TK63SLcMoW24pXCOhOqrSZMz495zt1KMp+zZ2x42o50HI5lal8JJ1f/ygetB1cnJFCGZs72yvY0/Fa8JWEe0USJE=
    - secure: CobH8rwCJY+XWFnwz9iPTM6GB5lnmSEaDfYC0KcsVzfI51PcY8fBHPXsaDnsIsNQWclPhSnEU4fUVwWmemL6z+O3XebCBBsWZVgjFajzwmS+76fuk8P+j8n+SYXUUDZNtx2d+NBe+D1MTn7GTIOPkz5SMDNLV4rbSUS+DeoY6JuF0LWtncENyBdqfy9tpiVikatN1Rp300dtR2gYIJT2uu1lhfGT7UXjoOdbVlDYmreaZsri5wU+vus1d9dyTbsd+TibbL3roCXYVWxqr3n2pqEvTpQyYf4WAgqJr9Hyhd/oC/My2XfGsB/l7KKVtl2EzM/ESME5AdUgaHFDs0pK1I7EBpzKq9HAMMkmmzAsrKZdsQcGRVYJnLPYCS9HByY2inbaVErX5ObHSQLf0fmOynjPByb0hCukvX3NmEzy4tNVvV4zWbX3saRrzzN8HwEhBCLmXKwja6an/kxVvadx3ilK7USvYoz9on32JLe/5WsrqH5NSzQTBNJvpc+vEduNIen2BGa42cdEVRi/MpbqAosGFMiydYLdmLNsZUdyGSSIB7yOL9Tm9K+o9J1pKP4Mnc5HVsgLU9cAMAlee2LidH0qAPH/nHQ+bdZTuQSZPSHkQM9j1KG++qkCQDM4QjW3XcoyXSS8O3ciiClAoYWonI7yxJ9xlGaLdvZlypTu8sM=
