sudo: required
services:
  - docker
dist: trusty
language: node_js
node_js:
  - '11'
after_success:
  - docker build -t jerrytfleung/primality .
after_script:
  - docker images
before_deploy:
  - echo $REGISTRY_USER
  - echo $REGISTRY_PASS
  - echo "$REGISTRY_PASS" | docker login --username jerrytfleung --password-stdin
deploy:
  provider: script
  script: docker push jerrytfleung/primality
  on:
    branch: master