sudo: required
services:
  - docker
dist: trusty
language: node_js
node_js:
  - '11'
after_success:
  - docker build -t jerrytfleung/primality .
after_script:
  - docker images
before_deploy:
  - echo $REGISTRY_USER
  - echo $REGISTRY_PASS
  - echo "$REGISTRY_PASS" | docker login --username jerrytfleung --password-stdin
deploy:
  provider: script
  script: docker push jerrytfleung/primality
  on:
    branch: master
env:
  global:
    secure: XPiIGTd/EkmrZFgDM8z6duCr+NuWZZNEOt2MXflpoQdlH8xTgWzRTu2crWXYqOpiq8Ckfm8bEKwxFcUOvsWZKTcrYR1HPP5atb1YO2VX/4dBH3+rzqcxmd6bISAlS0KaYGSqCbepFbJfCW/SVhjf1sg5Yw45dVZDRsIMHq3dtTW3wITQ1/2tRxY6yhVhvAX/RwbNFBxQvNB/4/gsoWbzEdgZWjzc2qAMdMIsX5uL03pOvbVFNuFpW8t8WcC9HKvwDk3h+mpQZ73gX4g95TEqzbu8bkAqalD3Ond3iW+ZSp0Ahuf/gVVHORWIsjfSo37RzFJT09bJk3BdxUpAMiqJQIXkjR4pMF9q6onEWg1uNJGAHNVDAzNBMseXcp1tqpt1u+vXanLMjjVlY5Cw+4S13Tv8o2SpOw5HzSWMAqBT6pBM9TUCZwFrA9vi+lrtd2FlnfzOTlJUHu0E3oNB9NHsFc3stgSnlG259xp0nocsBGoBf7dTg1R6BznH18uHdKb9i4BWt+uPybc2qWXtfuZ7vtS0Js1PtgYvF5vSOVcMd9m1IfsP+cV5l679upGPwf1utzQJ4ny9fCvz0quZGpM2GOBw/EaEUzGQ4ctkQ9uhNfmKL3qWXeOULL70TFIKRGlglFQZLvu0tWfP6FFCYE2RV23EMKaZhhQYP8HD7FFobMk=
